---
# defaults file for ansible-role-raspi-config

# specify whether to fail deployment when user/password is default
# ignored if "raspi_config_replace_user" is set (warning will still display)
raspi_config_fail_on_auth_test: true

# user to replace the default "pi" user with
# NOTE: if you use this for the first time as "pi", any post_tasks will fail!
raspi_config_replace_user:
  name:
  # LOCAL path to your public key file
  path_to_ssh_key:

# a dictionary of users to create
# Note: Can be used instead of replace user
# e.g. raspi_config_create_users:
#        - { name: 'piaware', path_to_ssh_key: "{{ playbook_dir }}/../../ssh_keys/{{ raspi_config_hostname }}.pub" }
raspi_config_create_users:

# wait this many seconds before forcing connection retry after reboot
raspi_config_reboot_max_wait_time: 300

raspi_config_bluetooth_services: [
  bluetooth,
  bluealsa,
  hciuart,
]

raspi_config_unwanted_services: [
  bluetooth,
  avahi-daemon,
  triggerhappy
]

# perform full update+upgrade
raspi_config_update_packages: true

# currently sets Pi2 OC setting if applicable
raspi_config_ensure_optimal_cpu_params: true

# 1. User Password

# 2. Network Options
raspi_config_network_hostname: pi
raspi_config_network_netnames: no

# 3. Boot Options
raspi_config_boot_behaviour: "B1" #B1 cli, B2 cli autologin, B3 desktop, B4 desktop autologin
raspi_config_boot_wait: no #False
raspi_config_boot_splash: "0" #0 Auto, 1 Force 3.5mm, 2 Force hdmi

# 4. Localisation Options
# set global locale
raspi_config_localisation_locale: 'fr_FR.UTF-8'
# set timezone
raspi_config_localisation_timezone: Europe/Paris #i.e. UTC, Europe/London, Australia/Adelaide
# list of services that should be restarted if the timezone is changed
raspi_config_localisation_timezone_dependent_services: []
# set keyboard layout
raspi_config_localisation_keyboard_layout: "fr" #default "gb"
# set Wifi country
raspi_config_localisation_wifi_country: "FR"

# 5. Interfacing Options
raspi_config_interface_enable_camera: no
raspi_config_interface_enable_ssh: yes
raspi_config_interface_enable_vnc: no
raspi_config_interface_enable_spi: no
raspi_config_interface_enable_i2c: no
raspi_config_interface_enable_serial: no
raspi_config_interface_enable_onewire: no
raspi_config_interface_enable_rgpio: no

# 6. Overclock Options
raspi_config_overclock: no
#see https://www.raspberrypi.org/documentation/configuration/config-txt/overclocking.md
#https://haydenjames.io/raspberry-pi-2-overclock/
#https://haydenjames.io/raspberry-pi-3-overclock/
#https://magpi.raspberrypi.org/articles/how-to-overclock-raspberry-pi-4
#OVERCLOCK:

# 7. Advanced Options
# have the FS fill the SD card
raspi_config_expanded_filesystem: yes
raspi_config_advanced_overscan: no # False
# how much memory should be owned by the GPU (vs RAM)
raspi_config_memory_split_gpu: 16
raspi_config_advanced_pixel_doubling: no
raspi_config_advanced_gldriver: no # False #G1 Full KMS, G2 Fake KMS, G3 Legacy
raspi_config_advanced_hdmi_group: no # False
raspi_config_advanced_hdmi_mod: no # False
raspi_config_advanced_audio_out: 0 #0 Auto #1 Force 3.5mm jack #2 Force HDMI
raspi_config_advanced_swapfile: 1 #0 to disable swap file

#Zram
# Based on
# https://ikarus.sg/using-zram-to-get-more-out-of-your-raspberry-pi/
zram: false

#log2ram:
# Based on https://levelup.gitconnected.com/extend-the-lifespan-of-your-raspberry-pis-sd-card-with-log2ram-5929bf3316f2
log2ram: false
