repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: flake8 .
        pass_filenames: false
        always_run: true
      - id: yamllint
        name: yamllint
        language: system
        entry: yamllint .
        pass_filenames: false
        always_run: true
      - id: ansible-lint
        name: Ansible-lint
        description: This hook runs ansible-lint.
        entry: ansible-lint --force-color .
        language: python
        # do not pass files to ansible-lint, see:
        # https://github.com/ansible/ansible-lint/issues/611
        pass_filenames: false
        always_run: true