---
- name: setup raspbian
  hosts: cluster, all
  remote_user: pi
  become: yes
  gather_facts: yes
  roles:
    - role: mikolak_net.raspi_config
      tags: raspi
    - role: common
      tags: common
    - role: users
      tags: users
    - role: nfs
      tags: nfs
    #- role: msmtpd
    #  tags: msmtpd

# ssh config
# fail2ban
# firewall ?
