- name: setup raspbian
  hosts: cluster
  remote_user: pi
  become: yes
  gather_facts: yes
  vars:
    #0 = active , 1= inactive
    CMDL: "dwc_otg.lpm_enable=0 console=tty1 fsck.mode=force cgroup_enable=memory cgroup_memory=1 cgroup_enable=cpuset"
  roles:
    - role: common
      tags: raspi
    - role: users
      tags: users
    - role: nfs
      tags: nfs
