---
- name: setup raspbian
  hosts: cluster
  remote_user: pi
  become: yes
  gather_facts: yes
  vars: []
  roles:
    - role: common
    - role: users
      tags: users
    - role: nfs
      tags: nfs

# ssh config
# fail2ban
# firewall ?
