---
- name: setup raspbian
  hosts: cluster, all
  remote_user: pi
  become: yes
  gather_facts: yes
  vars: []
  tasks:
    # ---- raspi ----
    - name: config raspi
      import_role:
        name: mikolak_net.raspi_config
      tags: raspi
  roles:
    - role: common
      tags: common
    - role: users
      tags: users
    - role: nfs
      tags: nfs

# ssh config
# fail2ban
# firewall ?
