---
collections: []

roles:
  # from GitHub, overriding the name and specifying a specific tag
  - name: mikolak_net.raspi_config
    src: https://github.com/edgd1er/ansible-raspi-config
    version: master
