---
# ---- prometheus ----
service_name: "prometheus"
user_id: "prometheus"
group_id: "prometheus"
exec_command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.conf --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d "
url_prefix: "https://github.com/prometheus/prometheus/releases/download"
prometheus_version: "2.28.0"
prometheus_port: "9091"
grafana_version: "7.0.0"
