---
# ------------ monitoring packages ------------
- name: install required packages
  apt:
    state: present
    pkg: "{{ required_packages }}"
    autoclean: true
    autoremove: true
    update_cache: true
  when: (required_packages is defined ) and (required_packages|length > 0)

# ------------ prometheus ------------
- name: get cpu info
  shell: "set -o pipefail; grep -Pom1 \"(?=ARM)([^ ]+)\" /proc/cpuinfo | tr '[:upper:]' '[:lower:]'"
  args:
    executable: "/usr/bin/bash"
  register: cpu_type
  changed_when: false

- name: get latest version
  shell: "set -o pipefail; curl --silent \"https://api.github.com/repos/prometheus/prometheus/releases/latest\" | grep -Pom1 \"(?=v)(.*)\""
  args:
    executable: "/usr/bin/bash"
  register: latest
  failed_when: false
  changed_when: false

- name: print latest
  debug:
    msg: >
      "cpu_type: {{ cpu_type.stdout }} prometheus latest: {{ latest.stdout }}"

- name: Display host
  debug:
    msg: >
      "inv_name: {{ inventory_hostname }}, ipv4: {{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}"

- name: 'Install packages'
  apt:
    pkg:
      - adduser
      - libfontconfig1

- name: Creating prometheus user group
  group: name="{{ group_id }}"
  become: yes
  become_user: root
  become_method: sudo

- name: Creating prometheus user
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "{{ user_id }}"
    group: "{{ group_id }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{ user_id }} nologin User"
    createhome: "no"
    state: present

- name: Install prometheus
  ansible.builtin.unarchive:
    src: >
      {{ url_prefix }}/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ cpu_type.stdout }}.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus file to bin
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ cpu_type.stdout }}/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    remote_src: yes
    mode: 0755

- name: Delete prometheus tmp folder
  file:
    path: '/tmp/prometheus-{{ prometheus_version }}.linux-{{ cpu_type.stdout }}'
    state: absent

- name: Creates directory
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "/data/prometheus/"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: 0755

- name: Creates directory
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "/etc/prometheus/"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: 0755

- name: prometheus config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf
    owner: prometheus
    group: prometheus
    mode: 0640

- name: Create systemd service file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0644
  notify: systemd_reload

- name: Start prometheus service
  become: yes
  become_user: root
  become_method: sudo
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200

- name: get cpu arch
  command: "dpkg --print-architecture"
  register: cpu_arch
  changed_when: false

- name: 'Download Grafana'
  get_url:
    url: 'https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_{{ cpu_arch.stdout }}.deb'
    dest: /tmp/

- name: 'Install Grafana'
  apt:
    deb: '/tmp/grafana_{{ grafana_version }}_{{ cpu_arch.stdout }}.deb'

- name: Start Grafana service
  become: yes
  become_user: root
  become_method: sudo
  service:
    name: grafana-server
    state: started
    enabled: yes
