---

# 7 Advanced Options

# A1 Expand Filesystem
- name: Check if FS is expandable
  shell: "raspi-config nonint get_can_expand"
  register: fs_filled
  changed_when: False

- name: Print if FS is expandable or not
  debug:
    msg: "Filesystem is expandable! [{{ fs_filled.stdout }}]"
  when: fs_filled.stdout == '0'

- name: Expand Filesystem
  shell: "raspi-config nonint do_expand_rootfs"
  when: raspi_config_expanded_filesystem and ( fs_filled.stdout == '0' )

# A2 Overscan
- name: Get Overscan status
  shell: "raspi-config nonint get_overscan"
  register: pi_overscan
  changed_when: False

- name: Print Overscan
  debug:
    msg: "Boot overscan is: {{ pi_overscan.stdout }}"

- name: Enable Overscan
  shell: "raspi-config nonint do_overscan {{ raspi_config_advanced_overscan }}"
  when: raspi_config_advanced_overscan

# A3 Memory Split
- name: Get current GPU memory split (1/4)
  shell: "raspi-config nonint get_config_var gpu_mem /boot/config.txt"
  register: gpu_mem
  changed_when: False

- name: Get current GPU memory split 256 (2/4)
  shell: "raspi-config nonint get_config_var gpu_mem_256 /boot/config.txt"
  register: gpu_mem_256
  changed_when: False

- name: Get current GPU memory split 512 (3/4)
  shell: "raspi-config nonint get_config_var gpu_mem_512 /boot/config.txt"
  register: gpu_mem_512
  changed_when: False

- name: Get current GPU memory split 1024 (4/4)
  shell: "raspi-config nonint get_config_var gpu_mem_1024 /boot/config.txt"
  register: gpu_mem_1k
  changed_when: False

- name: Print current GPU memory split
  debug:
    msg: "Expected: {{ raspi_config_memory_split_gpu }} - Current GPU memory split: {{ gpu_mem.stdout }} - {{ gpu_mem_256.stdout }} - {{ gpu_mem_512.stdout }} - {{ gpu_mem_1k.stdout }}"

- name: Set GPU memory split
  shell: "raspi-config nonint do_memory_split {{ raspi_config_memory_split_gpu }}"
  when: gpu_mem.stdout != raspi_config_memory_split_gpu

# A4 Audio
### 0 Auto, 1 Force 3.5mm, 2 Force hdmi
- name: Set audio out
  shell: "raspi-config nonint do_audio {{ raspi_config_advanced_audio_out }}"

# A5 Resolution
- name: Get HDMI group
  shell: "raspi-config nonint get_config_var hdmi_group /boot/config.txt"
  register: hdmi_group
  changed_when: False

- name: Get HDMI mode
  shell: "raspi-config nonint get_config_var hdmi_mode /boot/config.txt"
  register: hdmi_mode
  changed_when: False

- name: Print HDMI group & mode
  debug:
    msg: "HDMI group and mode is: {{ hdmi_group.stdout }} - {{ hdmi_mode.stdout }}"

  #- name: Set HDMI group mode
  #shell: "raspi-config nonint do_resolution {{ HDMI_GROUP }} {{ HDMI_MOD }}"

# A6 Pixel Doubling
- name: Get pixel doubling
  shell: "raspi-config nonint get_pixdub"
  register: pixdub_status
  changed_when: False

- name: Print pixel doubling status
  debug:
    msg: "Pixel Doubling is: {{ pixdub_status.stdout }}"

- name: Enable pixel doubling
  shell: "raspi-config nonint do_pixdub 0"
  when: (raspi_config_advanced_pixel_doubling) and (pixdub_status.stdout != '0')

- name: Disable pixel doubling
  shell: "raspi-config nonint do_onewire 1"
  when: (not raspi_config_advanced_pixel_doubling) and (pixdub_status.stdout != '1')

- name: Get swapfile status
  command: "swapon --noheadings --show=Size"
  register: swapon_size
  changed_when: False

- name: Print swapfile status
  debug:
    msg: "swapfile size is: {{ swapon_size.stdout }}"

- name: Disable default swap device
  command: "{{ item }}"
  args:
    warn: false # set warn=false to prevent warning
  with_items:
    - /bin/sed -i -E 's/(CONF_SWAPSIZE=)(.*)/\10/g' /etc/dphys-swapfile
    - /sbin/dphys-swapfile swapoff
    - /sbin/dphys-swapfile uninstall
    - /usr/sbin/update-rc.d dphys-swapfile remove
  when: (raspi_config_advanced_swapfile == 0) and (swapon_size.stdout != '')

- name: Enable default swap device
  command: "{{ item }}"
  args:
    warn: false # set warn=false to prevent warning
  with_items:
    - /bin/sed -i -E 's/(CONF_SWAPSIZE=)(.*)/\1100/g' /etc/dphys-swapfile
    - /sbin/dphys-swapfile swapon
    - /sbin/dphys-swapfile install
    - /usr/sbin/update-rc.d dphys-swapfile install
  when: (raspi_config_advanced_swapfile == 1) and (swapfile_size.stdout == '')

# A7 GL Driver
#- name: Set OpenGL desktop driver
#shell: "raspi-config nonint do_gldriver {{ raspi_config_advanced_gldriver }}"
