---

# Based on
# https://ikarus.sg/using-zram-to-get-more-out-of-your-raspberry-pi/

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: service_state.ansible_facts.services["zram-swap-config.service"].state

- name: Stop zram-swap-config service if running
  become: yes
  ansible.builtin.service:
    name: zram-swap-config
    state: stopped
  when: service_state.ansible_facts.services["zram-swap-config.service"] is defined

- name: Clone zram-config project
  ansible.builtin.git:
    repo: 'https://github.com/StuartIanNaylor/zram-swap-config.git'
    dest: /tmp/zram-swap-config

- name: Run the install script
  become: true
  command: ./install.sh
  register: zramres
  args:
    chdir: /tmp/zram-swap-config
  failed_when: zramres.sterr is defined
  changed_when: zramres.stdout|length > 0

- name: Print zram install output
  ansible.builtin.debug:
    var: zramres.stdout

- name: Cleanup installation files
  ansible.builtin.file:
    path: /tmp/zram-swap-config
    state: absent

- name: Disable default swap device
  command: "{{ item }}"
  register: disable
  with_items:
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - /usr/sbin/update-rc.d dphys-swapfile remove
  changed_when: false
