---
# enable nfs on server and client
nfs_enable: 1
# server with hd connected to
nfsserver_name: "netpi01"
nfsserver_exports: [ "/exports/master_data  192.168.53.0/24(rw,sync,root_squash,no_subtree_check)",
                     "/exports/cluster_data  192.168.53.0/24(rw,sync,root_squash,no_subtree_check)"]
nfsserver_rpcmountdopts: "--no-nfs-version 2 --no-nfs-version 3 --nfs-version 4 --no-udp"
nfsserver_rpcnfsdopts: "--no-nfs-version 2 --no-nfs-version 3 --nfs-version 4 --no-udp"
nfsserver_services:
  - nfs-server.service
nfsserver_quota_cluster: "200M 220M 0 0"
nfsserver_quota_master: "200M 220M 0 0"
# mount point for nfs server
mount_point_export_master: "/exports/master_data"
mount_point_export_cluster: "/exports/cluster_data"
# partition's names
cluster_name: "CLUSTER_DATA"
master_name: "MASTER_DATA"
# mount point for nfs client
mount_point_nfs: "/media/cluster_data"
# nfs quota
nfsclient_idmap: 'YES'
#  host.myserver.com:/home /mnt/home nfs rw,hard,intr,rsize=8192,wsize=8192,timeo=14 0 0
nfsclient_options: vers=4,rw,relatime,soft,_netdev,rsize=1048576,wsize=1048576,timeo=14,proto=tcp,port=2049,timeo=600,retrans=2,sec=sys,local_lock=none,clientaddr=
required_packages:
  - apt-transport-https
  - curl
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - nfs-common
  - quota

extra_packages:
  - sqlite3
  - samba
  - jq
  - wakeonlan
  - samba-client
  - mariadb-client
  - msmtp
  - msmtp-mta
