---
#enable nfs on server and client
nfs_enable: 1
#server with hd connected to
nfsserver_name: "netpi01"
nfsserver_exports: [ "/media/cluster_data  192.168.53.0/24(rw,sync,no_root_squash,no_subtree_check)" ]
nfsserver_services:
  - nfs-server.service
#mount point for nfs server
mount_point_usb: "/media/cluster_data"
usb_device: "/dev/sda5"
#mount point for nfs client
mount_point_nfs: "/media/cluster_data"
# host.myserver.com:/home /mnt/home nfs rw,hard,intr,rsize=8192,wsize=8192,timeo=14 0 0
nfsclient_options: rw,hard,rsize=8192,wsize=8192,timeo=14

required_packages:
  - apt-transport-https
  - curl
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - fail2ban
  - git
  - procps
  - iotop
  - nfs-common
  - dnsutils
  - cockpit
  - cockpit-docker
  - cockpit-storaged
  - cockpit-system
  - cockpit-pcp
  - nut-client
  - sysstat
  - vim
  - lsof

extra_packages:
  - sqlite3
  - samba
  - jq
  - wakeonlan
  - samba-client
  - mariadb-client
  - msmtp
  - msmtp-mta
