---

# Based on https://levelup.gitconnected.com/extend-the-lifespan-of-your-raspberry-pis-sd-card-with-log2ram-5929bf3316f2
- name: Stop log2ram service if running
  ansible.builtin.systemd:
    name: log2ram
    state: stopped
  failed_when: false

- name: Clone the log2ram repository
  ansible.builtin.git:
    repo: 'https://github.com/azlux/log2ram.git'
    dest: /tmp/log2ram
    version: master

- name: Install log2ram
  become: yes
  command: ./install.sh
  register: log2ramres
  args:
    chdir: /tmp/log2ram
    warn: no
  failed_when: (log2ramres.stdout is not defined ) or ( log2ramres.stdout |regex_search("ERROR") )
  changed_when: ( log2ramres.stdout is defined ) and ( log2ramres.stdout |regex_search("Reboot") )
  when: log2ram

- name: Print log2ram install output
  ansible.builtin.debug:
    var: log2ramres.stdout

- name: configure log2ram
  template:
    src: log2ram.conf.j2
    dest: /etc/log2ram.conf
    owner: root
    group: root
    mode: 0644

- name: Cleanup installation files
  ansible.builtin.file:
    path: /tmp/log2ram
    state: absent

- name: enable uninstall execution
  become: yes
  file:
    path: /usr/local/bin/uninstall-log2ram.sh
    mode: 0744
    owner: root
    group: root

- name: uninstall if requested
  command: /usr/local/bin/uninstall-log2ram.sh
  changed_when: false
  when: not log2ram and log2ram_uninstall
