---
# tasks file for ansible-role-raspi-config

- name: Assert remote is an RPi in expected state
  import_tasks: asserts.yml

- name: Get RPi version
  import_tasks: get-info.yml

- name: update all packages
  apt:
    update_cache: yes
    upgrade: dist
  when: raspi_config_update_packages

# done through user module in users role
# - name: 1-configure pi user
#  import_tasks: raspi-config-1-user-password.yml
- name: 2-configure raspberry network
  import_tasks: raspi-config-2-network-options.yml
  tags: raspi
- name: 3-configure raspi-config-3-boot-options
  import_tasks: raspi-config-3-boot-options.yml
  tags: raspi
- name: 4-configure localisation
  import_tasks: raspi-config-4-localisation-options.yml
  tags: raspi
- name: 5-configure raspberry interfaces camera, i2c,spi, serial, oneWire, remote GPIO, vnc, ssh,
  import_tasks: raspi-config-5-interfacing-options.yml
  tags: raspi
- name: 6-configure raspberry overclock
  import_tasks: raspi-config-6-overclock.yml
  tags: raspi
- name: 7-configure raspberry options
  import_tasks: raspi-config-7-advanced-options.yml
  tags: raspi

- name: package for ansible.builtin.expect
  apt:
    state: present
    pkg: "python3-pexpect"
    autoclean: true
    autoremove: true
    update_cache: true

- name: Set up zram-swap-config
  # https://github.com/StuartIanNaylor/zram-swap-config: I have problem with log2ram.
  import_tasks: zram-swap-config.yml
  when: zram|bool
  tags: zram

- name: Set up zram-swap
  # https://github.com/foundObjects/zram-swap
  import_tasks: zram-swap.yml
  when: _zram|bool
  tags: zram

- name: Set up log2ram
  import_tasks: log2ram.yml
  when: log2ram|bool
  tags: log2ram

- name: Disable services
  import_tasks: disable-services.yml
  notify:
    - reboot

- name: reboot
  become: yes
  ansible.builtin.reboot:
    reboot_timeout: "{{ raspi_config_reboot_max_wait_time }}"
  when: log2ram or zram or _zram

- name: wait for reboot
  wait_for_connection:
  delay: "{{ raspi_config_reboot_min_time }}"
  timeout: "{{ raspi_config_reboot_max_wait_time }}"
  when: log2ram or zram or _zram
