---

# Based on
# https://ikarus.sg/using-zram-to-get-more-out-of-your-raspberry-pi/

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services["zram-swap-config.service"].state
  when: ansible_facts.services["zram-swap-config.service"] is defined

- name: Stop zram-swap-config service if running
  become: yes
  ansible.builtin.service:
    name: zram-swap-config
    state: stopped
  when: >
    ( ansible_facts.services["zram-swap-config.service"] is defined ) and
    ( ansible_facts.services["zram-swap-config.service"].state == "running")

- name: Clone zram-config project
  ansible.builtin.git:
    repo: 'https://github.com/StuartIanNaylor/zram-swap-config.git'
    dest: /tmp/zram-swap-config

- name: Run the install script
  become: true
  command: ./install.sh
  register: zramres
  args:
    chdir: /tmp/zram-swap-config
  failed_when: ( zramres.sterr is defined ) and (zramres |regex_search("ERROR"))
  changed_when: zramres.stdout is defined

- name: Print zram install output
  ansible.builtin.debug:
    var: zramres.stdout

- name: configure zram-swap
  template:
    src: zram-swap-config.conf.j2
    dest: /etc/zram-swap-config.conf
    owner: root
    group: root
    mode: 0640

- name: Cleanup installation files
  ansible.builtin.file:
    path: /tmp/zram-swap-config
    state: absent

- name: Disable default swap device
  command: "{{ item }}"
  register: disable
  with_items:
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - /usr/sbin/update-rc.d dphys-swapfile remove
  changed_when: false

- name: uninstall
  become: yes
  shell: chmod +x /usr/local/bin/zram-swap-config-uninstall.sh && sudo /usr/local/bin/zram-swap-config-uninstall.sh
  changed_when: false
  when: not zram and zram_uninstall
