---
new_users:
  - { name: 'user', groups: 'sudo', home: '/home', pub_keys: '{{ pub_ssh_keys }}', password: '<hashed_password>' }

existing_users:
  - { name: 'pi', home: '/home', pub_keys: '{{ pub_ssh_keys }}', password: '<hashed_password>' }
  - { name: 'root', home: '/', pub_keys: '{{ pub_ssh_keys }}', password: '<hashed_password>' }

pub_ssh_keys:
  - "~/.ssh/key1.pub"
  - "~/.ssh/key1.pub"
  - "~/.ssh/key1.pub"

local_pub_keys_to_authorized:
  - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
