- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: started
