---
# Role raspi-config
# set global locale
raspi_config_locale: fr_FR.UTF-8
# set timezone
raspi_config_timezone: Europe/Paris
# enable ssh service
raspi_config_interface_enable_ssh: true
# ensure camera support is on - CURRENTLY UNVERIFIED
raspi_config_enable_camera: no
# how much memory should be owned by the GPU (vs RAM)
raspi_config_memory_split_gpu: 16
# perform full update+upgrade
raspi_config_update_packages: no
# have the FS fill the SD card
raspi_config_expanded_filesystem: yes
# currently sets Pi2 OC setting if applicable
raspi_config_ensure_optimal_cpu_params: no
# list of services that should be restarted if the timezone is changed
raspi_config_timezone_dependent_services: [ ]
# set hostname (defined with ansible_host)
# raspi_config_hostname: "{{ inventory_hostname }}"
# wait this many seconds before forcing connection retry after reboot
raspi_config_reboot_max_wait_time: 300
# use this to add any additional options to the config in raw form
raspi_config_other_options:
  - dwc_otg.lpm_enable=0
  - console=tty1
  - fsck.mode=force
  - cgroup_enable=memory
  - cgroup_memory=1
  - cgroup_enable=cpuset
# replace eth0 by a mac-addressed named interface
raspi_config_network_netnames: false
# enable swap file size, 0 to disable
raspi_config_advanced_swapfile: 0

# Zram: choose either zram-swap-config or zram-swap.
# Based on https://ikarus.sg/using-zram-to-get-more-out-of-your-raspberry-pi/
zram: false
zram_uninstall: false

# install zram-swap : https://github.com/foundObjects/zram-swap.git
_zram: true
_zram_uninstall: false

# log2ram:
# Based on https://levelup.gitconnected.com/extend-the-lifespan-of-your-raspberry-pis-sd-card-with-log2ram-5929bf3316f2
# ZL2R Zram Log 2 Ram enables a zram drive when ZL2R=true ZL2R=false is mem only tmpfs
log2ram: true
# Size for the ram folder, it defines the size the log folder will reserve into the RAM.
log2ram_size: 100M
# If there are some errors with available RAM space, a system mail will be send
# Change it to false and you will have only a log if there is no place on RAM anymore.
log2ram_mail: true
# ZL2R Zram Log 2 Ram enables a zram drive when ZL2R=true ZL2R=false is mem only tmpfs
log2ram_zl2r: true
# COMP_ALG this is any compression algorithm listed in /proc/crypto
log2ram_comp_alg: zstd
# Really a guestimate of a bit bigger than compression ratio whilst minimising 0.1% mem usage of disk size
log2ram_uncompressed_disk_size: 280M

# ---- sysstat ----
sysstat: true