---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible-core yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint -c .yamllint .
          ansible-lint

      - name: Lint Ansible Playbook
        # replace "master" with any valid ref
        #uses: ansible/ansible-lint-action@master
        uses: iranzo/ansible-lint-action@v4.1.1
        with:
          # [required]
          # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
          # or valid Ansible directories according to the Ansible role
          # directory structure.
          # If you want to lint multiple ansible files, use the following syntax
          # targets: |
          #   playbook_1.yml
          #   playbook_2.yml
          targets: "./"
          # [optional]
          # Arguments to override a package and its version to be set explicitly.
          # Must follow the example syntax.
          override-deps: |
            ansible==2.9
            ansible-lint==4.3.7
          # [optional]
          # Arguments to be passed to the ansible-lint

          # Options:
          #   -q                    quieter, although not silent output
          #   -p                    parseable output in the format of pep8
          #   --parseable-severity  parseable output including severity of rule
          #   -r RULESDIR           specify one or more rules directories using one or
          #                         more -r arguments. Any -r flags override the default
          #                         rules in ansiblelint/rules, unless -R is also used.
          #   -R                    Use default rules in ansiblelint/rules in addition to
          #                         any extra
          #                         rules directories specified with -r. There is no need
          #                         to specify this if no -r flags are used
          #   -t TAGS               only check rules whose id/tags match these values
          #   -x SKIP_LIST          only check rules whose id/tags do not match these
          #                         values
          #   --nocolor             disable colored output
          #   --exclude=EXCLUDE_PATHS
          #                         path to directories or files to skip. This option is
          #                         repeatable.
          #   -c C                  Specify configuration file to use. Defaults to ".ansible-lint"
          args: ""
